version: '3.9'
services:
  web:
    image: "conorshort/calendarap"
    command: >
      bash -c "python manage.py collectstatic      
      && gunicorn --bind :8000 --workers 3 calendarproj.wsgi:application"
    ports:
      - "80:8000"
    volumes:
        - ./conf/:/code/conf