# Generated by Django 3.1 on 2020-11-09 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shared_with',
            field=models.ManyToManyField(related_name='_user_shared_with_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
