# Generated by Django 3.1 on 2020-11-09 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20201109_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='_user_shared_with_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
