# Generated by Django 3.1 on 2020-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20201109_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
