# Generated by Django 3.1 on 2020-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_event_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
